### PR TITLE
fix #68

### LINKED ISSUE #68: Download fails due to expired cache.e.ip.saba.us SSL certificate
When after running Pkg.update() Pkg.build("Nettle") failed due to Pkg.build("WinRPM") failing.
So this is what happens:
```julia
julia> Pkg.build("WinRPM")
INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270105
WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
```

### PR DESCRIPTION
**Pull request by mlubin**
As suggested by @staticfloat.
CC @rapus95 @nalimilan

### CODE REVIEW

**Comment by mlubin** [comment]
I tested and this seems to be working. Any objection to merging @nalimilan?

**Comment by nalimilan** [comment]
Sure.

**Comment by mlubin** [comment]
Who wants to tag?

**Comment by nalimilan** [comment]
Go ahead!

**Comment by mlubin** [comment]
Does ``Pkg.publish()`` not work on windows??
```
julia> Pkg.publish()
INFO: Validating METADATA
INFO: Pushing WinRPM permanent tags: v0.1.15
INFO: Submitting METADATA changes
INFO: Forking JuliaLang/METADATA.jl to mlubin
ERROR: could not spawn `curl --version`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
```
Anyway I'll do it manually

**Comment by nalimilan** [comment]
No idea. Anyway this has been ported to libgit2 in 0.5, could fix it.

**Comment by nalimilan** [comment]
(I can do it instead if you like.)

**Pull request merged**
