### PR TITLE
Remove some no longer relevant code

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by tkelman** [comment]
there are 3 other versions checks against 0.3, may as well get rid of those too

**Comment by IainNZ** [comment]
I was just doing random edits in the browser as I looked over why exactly this package needs HTTPClient

**Comment by IainNZ** [comment]
OK, got them I think

**Comment by tkelman** [comment]
yeah, lgtm. will leave open a bit if anyone else wants to double-check

**Pull request merged**
