### PR TITLE
Stop using HTTPClient

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by IainNZ** [comment]
HTTPClient/LibCurl doesn't pass tests on 0.4, not that this branch ever gets used I guess.

**Comment by tkelman** [comment]
This would leave temp file litter around and never clean up after itself?

**Comment by IainNZ** [comment]
On OSX `Base.download` puts into a temporary files folder that OSX cleans, I'm not sure what Linux behaviour is.

**Comment by IainNZ** [comment]
(this is really a drive-by PR, I was just reminded of this by the 'cycle' it induces while updated MetadataTools.jl)

**Comment by IainNZ** [comment]
Bump @tkelman. Any reason to believe this wouldn't be an improvement for the better?

**Comment by tkelman** [comment]
Because `Base.download` is pretty limited, you're totally faking the return code, and not cleaning up temporary files.

**Pull request closed without merging**
