### PR TITLE
Fall back to opensuse servers

### PR DESCRIPTION
**Pull request by mlubin**
Temporary workaround for #68
CC @rapus95 @nalimilan

### CODE REVIEW

**Comment by mlubin** [comment]
@rapus95 could you confirm this works?

**Comment by nalimilan** [comment]
What happens if you keep the old lines at the top, but add the others as backup?

**Comment by mlubin** [comment]
I don't know enough about WinRPM to say.

**Comment by nalimilan** [comment]
Maybe @rapus95 can test this for us?

**Pull request closed without merging**
